#!/usr/bin/env python3
"""Market-structure evaluation over 2 years of daily history.

- Fractal swing detection (k=3, confirmed only — a swing needs 3 closed
  candles on each side, so there is no hindsight bias at the right edge).
- Trend state from the last two swing highs + lows (HH/HL vs LH/LL).
- Active MSL (structure stop) and MSH (breakout level), ATR(14) buffer.
- Support/resistance zones: all historical swing points clustered by price;
  zones = clusters with >= 3 touches.

Writes structure.js (read by detail.html and check_alerts.py).
Refresh: fetch raw_history/{sym}.json (range=2y&interval=1d), then run this.
"""
import json
import os
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SYMBOLS = [("2344.TW", "2344"), ("2337.TW", "2337"), ("6770.TW", "6770"),
           ("1307.TW", "1307"), ("NVDA", "NVDA"), ("AAPL", "AAPL")]
K = 3          # fractal half-width
WINDOW = 190   # candles shown on the structure chart
MIN_TOUCHES = 3


def load(yahoo):
    d = json.load(open(os.path.join(HERE, "raw_history", f"{yahoo}.json")))
    r = d["chart"]["result"][0]
    q = r["indicators"]["quote"][0]
    off = r["meta"].get("gmtoffset", 0)
    out = []
    for i, ts in enumerate(r["timestamp"]):
        o, h, l, c = q["open"][i], q["high"][i], q["low"][i], q["close"][i]
        if None in (o, h, l, c):
            continue
        out.append({"d": time.strftime("%Y-%m-%d", time.gmtime(ts + off)),
                    "o": round(o, 2), "h": round(h, 2), "l": round(l, 2),
                    "c": round(c, 2), "v": q["volume"][i] or 0})
    return out


def fractal_swings(cs, k=K):
    sw = []
    for i in range(k, len(cs) - k):
        hs = [cs[j]["h"] for j in range(i - k, i + k + 1)]
        ls = [cs[j]["l"] for j in range(i - k, i + k + 1)]
        if cs[i]["h"] == max(hs) and hs.count(cs[i]["h"]) == 1:
            sw.append({"i": i, "d": cs[i]["d"], "p": cs[i]["h"], "t": "H"})
        elif cs[i]["l"] == min(ls) and ls.count(cs[i]["l"]) == 1:
            sw.append({"i": i, "d": cs[i]["d"], "p": cs[i]["l"], "t": "L"})
    return sw


def atr14(cs):
    trs = [max(cs[i]["h"] - cs[i]["l"],
               abs(cs[i]["h"] - cs[i - 1]["c"]),
               abs(cs[i]["l"] - cs[i - 1]["c"])) for i in range(1, len(cs))]
    if len(trs) < 14:
        return None
    a = sum(trs[:14]) / 14
    for tr in trs[14:]:
        a = (a * 13 + tr) / 14
    return a


def cluster_zones(swings, last_close, atr):
    tol = max(last_close * 0.015, (atr or 0) * 0.5)
    pts = sorted((s["p"], s["t"]) for s in swings)
    if not pts:
        return []
    groups, cur = [], [pts[0]]
    for p in pts[1:]:
        # chain nearby points, but cap zone width so a long base can't merge into one mega-zone
        if p[0] - cur[-1][0] <= tol and p[0] - cur[0][0] <= tol * 2.5:
            cur.append(p)
        else:
            groups.append(cur)
            cur = [p]
    groups.append(cur)
    zones = []
    for gp in groups:
        if len(gp) < MIN_TOUCHES:
            continue
        lo, hi = gp[0][0], gp[-1][0]
        mid = (lo + hi) / 2
        zones.append({"lo": round(lo, 2), "hi": round(hi, 2), "n": len(gp),
                      "kind": "support" if mid <= last_close else "resistance"})
    zones.sort(key=lambda z: -z["n"])
    return zones[:8]


out = {}
for yahoo, key in SYMBOLS:
    cs = load(yahoo)
    swings = fractal_swings(cs)
    atr = atr14(cs)
    last = cs[-1]["c"]
    highs = [s for s in swings if s["t"] == "H"]
    lows = [s for s in swings if s["t"] == "L"]
    trend = "mixed"
    if len(highs) >= 2 and len(lows) >= 2:
        hh, hl = highs[-1]["p"] > highs[-2]["p"], lows[-1]["p"] > lows[-2]["p"]
        lh, ll = highs[-1]["p"] < highs[-2]["p"], lows[-1]["p"] < lows[-2]["p"]
        trend = "up" if (hh and hl) else "down" if (lh and ll) else "mixed"
    start = max(0, len(cs) - WINDOW)
    win_swings = [{"i": s["i"] - start, "d": s["d"], "p": s["p"], "t": s["t"]}
                  for s in swings if s["i"] >= start]
    out[key] = {
        "sessions": len(cs),
        "span": [cs[0]["d"], cs[-1]["d"]],
        "trend": trend,
        "msl": {"p": lows[-1]["p"], "d": lows[-1]["d"]} if lows else None,
        "msh": {"p": highs[-1]["p"], "d": highs[-1]["d"]} if highs else None,
        "atr": round(atr, 2) if atr else None,
        "stopBuf": round(lows[-1]["p"] - atr, 2) if (lows and atr) else None,
        "zones": cluster_zones(swings, last, atr),
        "candles": cs[start:],
        "swings": win_swings,
    }

with open(os.path.join(HERE, "structure.js"), "w") as f:
    f.write("// Generated by build_structure.py — 2y market structure (fractal swings, zones)\n")
    f.write("// Generated at: " + time.strftime("%Y-%m-%d %H:%M") + "\n")
    f.write("const STRUCTURE = " + json.dumps(out, ensure_ascii=False) + ";\n")

for k, v in out.items():
    print(f"{k}: {v['sessions']} sessions, trend={v['trend']}, "
          f"MSL={v['msl'] and v['msl']['p']}, MSH={v['msh'] and v['msh']['p']}, "
          f"ATR={v['atr']}, zones={len(v['zones'])}")
