#!/usr/bin/env python3
"""Rebuild data.js from Yahoo Finance raw JSON.

Refresh workflow:
  cd site
  for s in 2344.TW 2337.TW 6770.TW NVDA BTC-USD ETH-USD; do
    curl -s -H "User-Agent: Mozilla/5.0" \
      "https://query1.finance.yahoo.com/v8/finance/chart/${s}?range=1mo&interval=1d" \
      -o "raw/${s}.json"
  done
  python3 build_data.py
"""
import json
import time
import os

HERE = os.path.dirname(os.path.abspath(__file__))

SYMBOLS = [
    ("2344.TW", "2344", "Winbond 華邦電"),
    ("2337.TW", "2337", "Macronix 旺宏"),
    ("6770.TW", "6770", "Powerchip 力積電"),
    ("1307.TW", "1307", "San Fang 三芳"),
    ("NVDA", "NVDA", "NVIDIA"),
    ("AAPL", "AAPL", "Apple"),
    ("SPCX", "SPCX", "SpaceX"),
]

def volume_profile(yahoo, bins=24):
    """Volume-at-price from 5d/15m bars; falls back to None if file missing/bad."""
    try:
        with open(os.path.join(HERE, "raw_intraday", f"{yahoo}.json")) as f:
            d = json.load(f)
        r = d["chart"]["result"][0]
        q = r["indicators"]["quote"][0]
        pts = []
        for i in range(len(r["timestamp"])):
            h, l, c, v = q["high"][i], q["low"][i], q["close"][i], q["volume"][i]
            if None in (h, l, c) or not v:
                continue
            pts.append(((h + l + c) / 3, v))
        if len(pts) < 10:
            return None
        lo = min(p for p, _ in pts)
        hi = max(p for p, _ in pts)
        if hi <= lo:
            return None
        vols = [0] * bins
        for p, v in pts:
            idx = min(int((p - lo) / (hi - lo) * bins), bins - 1)
            vols[idx] += v
        return {"lo": round(lo, 2), "hi": round(hi, 2), "bins": vols}
    except Exception:
        return None


out = {}
for yahoo, key, label in SYMBOLS:
    with open(os.path.join(HERE, "raw", f"{yahoo}.json")) as f:
        d = json.load(f)
    r = d["chart"]["result"][0]
    meta = r["meta"]
    q = r["indicators"]["quote"][0]
    candles = []
    for i, ts in enumerate(r["timestamp"]):
        o, h, l, c = q["open"][i], q["high"][i], q["low"][i], q["close"][i]
        if None in (o, h, l, c):
            continue
        v = q["volume"][i] or 0
        day = time.strftime("%m-%d", time.gmtime(ts + meta.get("gmtoffset", 0)))
        candles.append({
            "d": day,
            "o": round(o, 2), "h": round(h, 2),
            "l": round(l, 2), "c": round(c, 2),
            "v": v,
        })
    out[key] = {
        "label": label,
        "currency": meta.get("currency", ""),
        "candles": candles[-24:],
        "profile": volume_profile(yahoo),
    }

with open(os.path.join(HERE, "data.js"), "w") as f:
    f.write("// Generated by build_data.py — candle data from Yahoo Finance (daily)\n")
    f.write("// Generated at: " + time.strftime("%Y-%m-%d %H:%M %Z") + "\n")
    f.write("const STOCK_DATA = ")
    f.write(json.dumps(out, ensure_ascii=False, indent=1))
    f.write(";\n")
    f.write('const GENERATED_AT = "' + time.strftime("%Y-%m-%d %H:%M") + '";\n')

print("data.js written:", ", ".join(f"{k}({len(v['candles'])})" for k, v in out.items()))
